fix msk test

diff --git a/managed-streaming-kafka-cluster/Makefile b/managed-streaming-kafka-cluster/Makefile
--- a/managed-streaming-kafka-cluster/Makefile
+++ b/managed-streaming-kafka-cluster/Makefile
@@ -30,13 +30,22 @@ init:
 	tflocal init
 
 deploy:
-	tflocal apply --auto-approve; \
-	awslocal awslocal kafka list-clusters;
+	tflocal apply --auto-approve
 
-run: start install init deploy
+test:
+	@awslocal kafka list-clusters > cluster_info.json
+	@cat cluster_info.json
+	@if cat cluster_info.json | jq -e '.ClusterInfoList[0].ClusterName == "example" and .ClusterInfoList[0].State == "ACTIVE"' > /dev/null; then \
+	    echo "Smoke test passed: Cluster name is 'example' and state is 'ACTIVE'."; \
+	else \
+	    echo "Smoke test failed: Cluster name or state is incorrect."; \
+	    exit 1; \
+	fi
+
+run: start install init deploy test
 
 test-ci:
-	make start install init deploy; return_code=`echo $$?`;\
+	make start install init deploy test; return_code=`echo $$?`;\
 	make logs; make stop; exit $$return_code;
 
 clean:
